Fixed community tag
JumpCutter/JC-locales pull request #6
Opened 2022-03-07 11:45 UTC by victormihalache

2022-03-07 16:24 UTC, 19wintersp commented on locales.json
> +    "community: true,
Trailing comma?

2022-03-07 16:26 UTC, 19wintersp requested changes
Please can you try to check that this definitely works. Standard JSON also does not permit trailing commas, and NodeJS (at least my installation) does not either.

2022-03-15 19:59 UTC, victormihalache commented
> Please can you try to check that this definitely works. Standard JSON also does not permit trailing commas, and NodeJS (at least my installation) does not either.

Should now work, dunno how i missed that.

2022-03-15 20:00 UTC, 19wintersp approved these changes
As long as you've checked it works on a full build, this is fine.

2022-03-24 20:45 UTC, Dreiparrent approved these changes

2022-03-24 20:45 UTC, merged